
import HomeLogo from './HomeLogo.png';
import TwitterLogo from './TwitterLogo.png';
import DiscordLogo from './DiscordLogo.png';
import OSLogo from './OSLogo.png';
import './App';
import styled from "styled-components";
import { Link } from 'react-router-dom';

export const StyledButton = styled.button`
  padding: 10px;
  border-radius: 50px;
  border: none;
  background-color: #000000;
  padding: 10px;
  font-weight: 800;
  color: #FFFFFF;
  width: 100px;
  cursor: pointer;
  :active {
    box-shadow: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
  }
`;

const Home = () => {
    return (
        
        <body className="cust" style={{
            textAlign: "center"

        }}>            
            <br></br>
            <h1> <img src={HomeLogo} alt="loading..." style={{
                height: 150,
                width: 500
            }} /> </h1>               
                <a href="https://www.twitter.com/abstrctnumbers">
                    <img src={TwitterLogo} alt="loading..." style={{
                        height: 24,
                        padding: 2,
                        width: 24
                    }} />
                </a>
                <a href="https://discord.gg/a3re3sSPHs">
                    <img src={DiscordLogo} alt="loading..." style={{
                        height: 24,
                        padding: 2,
                        width: 24
                    }} />
                </a>
                <a href="https://www.opensea.io">
                    <img src={OSLogo} alt="loading..." style={{
                        height: 24,
                        padding: 2,
                        width: 24
                    }} />
                </a>
                <br></br><br></br><br></br><br></br><br></br>

            <h2 style={{
                padding: "5px",
                fontSize: "2rem"
            }}>About</h2>
            <strong><p style ={{
                fontSize:"20px"
            }}>
                Numbers is the first collection consisting <br></br>
                of 2021 interactive numbers stored on the Ethereum blockchain.<br></br>
                Each number is completely generated by code and permanently stored on IPFS.
                </p><br></br><br></br><br></br>
                <h2 style={{
                    padding: "5px",
                    fontSize: "2rem"
                }}>Fair Launch</h2>
                <p style ={{
                fontSize:"20px"
            }}>
                The traits for each number will be generated upon mint<br></br>
                This ensures a fair & transparent launch because rarity will<br></br>
                be chosen randomly by the minters!<br></br>
                  </p></strong>
                 <br></br>

            <br></br><br></br>

            <h2 style={{
                padding: "5px",
                fontSize: "2rem"
            }}>When</h2>
            <strong><p style ={{
                fontSize:"20px"
            }}>
                The public sale date hasn't been chosen yet.<br></br>
                Aiming to launch near the end of this month (november) the latest.
            </p></strong>
            <br></br><br></br><br></br>
            <Link to="/mint">
                <StyledButton>MINT</StyledButton>
            </Link>
            <br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br>
        </body>
    );
}


export default Home;
